// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzxmddvlyrzlnrozplox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6eG1kZHZseXJ6bG5yb3pwbG94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2ODk0ODMsImV4cCI6MjA3MzI2NTQ4M30.VCfdpBT2aj-RK2SmZbhbk_hVRCYRhggBv8fibdEKzmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});